# Generated by Django 4.0 on 2021-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nb_piece', models.IntegerField()),
                ('typologie', models.CharField(max_length=20)),
                ('prix_tva_reduite', models.FloatField(null=True)),
                ('prix_tva_normale', models.FloatField(null=True)),
                ('prix_HT', models.FloatField(null=True)),
                ('prix_m2_HT', models.FloatField(null=True)),
                ('prix_m2_TTC', models.FloatField(null=True)),
                ('surface', models.FloatField()),
                ('etage', models.IntegerField(null=True)),
                ('orientation', models.CharField(max_length=50)),
                ('exterieur', models.CharField(max_length=10)),
                ('balcony', models.CharField(max_length=10)),
                ('garden', models.CharField(max_length=10)),
                ('parking', models.CharField(max_length=10)),
                ('nom_programme', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=80)),
                ('departement', models.IntegerField()),
                ('data_fin_prog', models.DateField()),
                ('adresse', models.CharField(max_length=100)),
                ('promoteur', models.CharField(max_length=50)),
                ('date_extraction', models.DateField()),
            ],
        ),
    ]
