# Generated by Django 4.0 on 2021-12-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_CSV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immo',
            name='id_lot',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
