# Generated by Django 4.0 on 2021-12-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Upload_CSV', '0002_immo_id_lot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immo',
            old_name='data_fin_prog',
            new_name='date_fin_prog',
        ),
    ]
